#!/bin/sh
# A configure step: it writes a header by TESTING the host, not by asserting
# things about it.
#
# This is the shape every autotools package has, without the four thousand lines
# of generated shell. Two things about it matter to a corpus:
#
#   * the file main.c includes does not exist in the shipped package. Anything
#     that assumes the source tree it received is the source tree the compiler
#     sees is wrong here;
#   * the test is a real compile. It invokes $CC, it can fail, and its result
#     changes the product.
#
# Deterministic on any host that has a C compiler: the answers below are all
# "yes" everywhere this corpus is built, and the specimen declares them.
set -eu

out="$1"
CC=${CC:-cc}
tmp="./.configure-probe"

probe_header() {
    printf '#include <%s>\nint main(void){return 0;}\n' "$1" > "$tmp.c"
    if $CC -c -o "$tmp.o" "$tmp.c" >/dev/null 2>&1; then
        echo 1
    else
        echo 0
    fi
    rm -f "$tmp.c" "$tmp.o"
}

have_stdint=$(probe_header stdint.h)
have_unistd=$(probe_header unistd.h)
have_nonexistent=$(probe_header lexe/definitely-not-a-header.h)

{
    echo '/* GENERATED by configure.sh at build time -- do not edit, and do not'
    echo '   expect to find this file in the package. */'
    echo '#ifndef PORTABLE_CONFIG_H'
    echo '#define PORTABLE_CONFIG_H'
    echo '#define CONFIG_STAMP "configured-v1"'
    echo "#define CONFIG_HAVE_STDINT $have_stdint"
    echo "#define CONFIG_HAVE_UNISTD $have_unistd"
    echo "#define CONFIG_HAVE_NONSENSE $have_nonexistent"
    echo '#endif'
} > "$out"

echo "configure.sh: wrote $out"
